<a href="https://colab.research.google.com/github/amberyliang/Big-Data-Analytics-and-Application-Course/blob/main/week3_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import pandas as pd
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [50]:
x = pd.DataFrame(iris["data"], columns = iris["feature_names"])
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [51]:
y = pd.DataFrame(iris["target"], columns = ["target_names"])
y

target_names
0               0
1               0
2               0
3               0
4               0
..            ...
145             2
146             2
147             2
148             2
149             2

[150 rows x 1 columns]

In [52]:
data = pd.concat([x,y], axis = 1)
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target_names  
0               0  
1               0  
2               0  
3               0  
4               0  
..            ...  
145             2  
146             2  
147             2  
148             2  
149             2  

[150 rows x 5 columns]

Call out another array "target" in iris dataset and use "target_name" as column names

#Using concat( ) to combine iris dataset and target array.

In [53]:
data = pd.concat([x,y], axis = 1)
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target_names  
0               0  
1               0  
2               0  
3               0  
4               0  
..            ...  
145             2  
146             2  
147             2  
148             2  
149             2  

[150 rows x 5 columns]

In [54]:
from sklearn import preprocessing as pp
from sklearn import impute as ip
#print(data.mean())
#scale()是對數據進行z-score標準化
scaled = pp.scale(data)
pp.normalize(data)
pp.binarize(scaled,threshold=-1) #使用z-score後再套入二分法/threshold預設為0


array([[1., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 1.

#Use DataFrame type to do binarize
applymap(lambda ) x> -1 --> 1 else 0\
*applymap speculatly use DataFrame type

In [55]:
df_scaled = pd.DataFrame(scaled, columns = data.columns)
print(df_scaled.head(3))
df_scaled.applymap(lambda x:1  if x>-1 else 0)
transformer = pp.FunctionTransformer(lambda scaled:[1 if y > -1 else 0 for y in x]for x in scaled)
print(transformer)

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0          -0.900681          1.019004          -1.340227         -1.315444   
1          -1.143017         -0.131979          -1.340227         -1.315444   
2          -1.385353          0.328414          -1.397064         -1.315444   

   target_names  
0     -1.224745  
1     -1.224745  
2     -1.224745  
FunctionTransformer(func=<generator object <genexpr> at 0x7d1a8f4de0a0>)


<ipython-input-55-0db22ba1c671>:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_scaled.applymap(lambda x:1  if x>-1 else 0)


#Use transformer( ) to do binary preprocessing

In [56]:

scaled = pp.scale(df_scaled)
print(scaled[:3])
transformer = pp.FunctionTransformer(lambda x: np.array([[1 if y > -1 else 0 for y in row] for row in x]))
transformed_data = transformer.transform(scaled)
print(transformed_data[:3])

[[-0.90068117  1.01900435 -1.34022653 -1.3154443  -1.22474487]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443  -1.22474487]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443  -1.22474487]]
[[1 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]]
